### PR TITLE
Cleanup unused

### PR DESCRIPTION
**Pull request by geoand**
These left-over files create confusion as to whether they are still
being used or not

### CODE REVIEW

**Comment by metacosm** [comment]
@cmoulliard wanted to keep some of these files but I don't know what for…

**Comment by geoand** [comment]
OK, so I guess @cmoulliard will decide then :)

The reason I opened this is that as someone who is going through the code to understand all the moving parts, having out of dates bit like this is confusing and makes it difficult to reason about which parts are actually being used

**Comment by cmoulliard** [comment]
I will make a copy of those files locally.

**Comment by geoand** [comment]
Sounds good, thanks!

**Pull request merged**
